// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/math.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Shared.Protos {
  public static partial class MathService
  {
    static readonly string __ServiceName = "MathPackage.MathService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Shared.Protos.FactorialRequest> __Marshaller_MathPackage_FactorialRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Shared.Protos.FactorialRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Shared.Protos.FactorialResponse> __Marshaller_MathPackage_FactorialResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Shared.Protos.FactorialResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Shared.Protos.AverageNumbersRequest> __Marshaller_MathPackage_AverageNumbersRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Shared.Protos.AverageNumbersRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Shared.Protos.AverageNumbersResponse> __Marshaller_MathPackage_AverageNumbersResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Shared.Protos.AverageNumbersResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Shared.Protos.SumNumbersRequest> __Marshaller_MathPackage_SumNumbersRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Shared.Protos.SumNumbersRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Shared.Protos.SumNumbersResponse> __Marshaller_MathPackage_SumNumbersResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Shared.Protos.SumNumbersResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Shared.Protos.FactorialRequest, global::Shared.Protos.FactorialResponse> __Method_Factorial_ServerStreaming = new grpc::Method<global::Shared.Protos.FactorialRequest, global::Shared.Protos.FactorialResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "Factorial_ServerStreaming",
        __Marshaller_MathPackage_FactorialRequest,
        __Marshaller_MathPackage_FactorialResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Shared.Protos.AverageNumbersRequest, global::Shared.Protos.AverageNumbersResponse> __Method_Average_ClientStreaming = new grpc::Method<global::Shared.Protos.AverageNumbersRequest, global::Shared.Protos.AverageNumbersResponse>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "Average_ClientStreaming",
        __Marshaller_MathPackage_AverageNumbersRequest,
        __Marshaller_MathPackage_AverageNumbersResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Shared.Protos.SumNumbersRequest, global::Shared.Protos.SumNumbersResponse> __Method_Sum_ClientServerBothStreaming = new grpc::Method<global::Shared.Protos.SumNumbersRequest, global::Shared.Protos.SumNumbersResponse>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "Sum_ClientServerBothStreaming",
        __Marshaller_MathPackage_SumNumbersRequest,
        __Marshaller_MathPackage_SumNumbersResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Shared.Protos.MathReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of MathService</summary>
    [grpc::BindServiceMethod(typeof(MathService), "BindService")]
    public abstract partial class MathServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task Factorial_ServerStreaming(global::Shared.Protos.FactorialRequest request, grpc::IServerStreamWriter<global::Shared.Protos.FactorialResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Shared.Protos.AverageNumbersResponse> Average_ClientStreaming(grpc::IAsyncStreamReader<global::Shared.Protos.AverageNumbersRequest> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task Sum_ClientServerBothStreaming(grpc::IAsyncStreamReader<global::Shared.Protos.SumNumbersRequest> requestStream, grpc::IServerStreamWriter<global::Shared.Protos.SumNumbersResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for MathService</summary>
    public partial class MathServiceClient : grpc::ClientBase<MathServiceClient>
    {
      /// <summary>Creates a new client for MathService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public MathServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for MathService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public MathServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected MathServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected MathServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Shared.Protos.FactorialResponse> Factorial_ServerStreaming(global::Shared.Protos.FactorialRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Factorial_ServerStreaming(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Shared.Protos.FactorialResponse> Factorial_ServerStreaming(global::Shared.Protos.FactorialRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_Factorial_ServerStreaming, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::Shared.Protos.AverageNumbersRequest, global::Shared.Protos.AverageNumbersResponse> Average_ClientStreaming(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Average_ClientStreaming(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::Shared.Protos.AverageNumbersRequest, global::Shared.Protos.AverageNumbersResponse> Average_ClientStreaming(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_Average_ClientStreaming, null, options);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::Shared.Protos.SumNumbersRequest, global::Shared.Protos.SumNumbersResponse> Sum_ClientServerBothStreaming(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Sum_ClientServerBothStreaming(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::Shared.Protos.SumNumbersRequest, global::Shared.Protos.SumNumbersResponse> Sum_ClientServerBothStreaming(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_Sum_ClientServerBothStreaming, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override MathServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new MathServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(MathServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Factorial_ServerStreaming, serviceImpl.Factorial_ServerStreaming)
          .AddMethod(__Method_Average_ClientStreaming, serviceImpl.Average_ClientStreaming)
          .AddMethod(__Method_Sum_ClientServerBothStreaming, serviceImpl.Sum_ClientServerBothStreaming).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, MathServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Factorial_ServerStreaming, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Shared.Protos.FactorialRequest, global::Shared.Protos.FactorialResponse>(serviceImpl.Factorial_ServerStreaming));
      serviceBinder.AddMethod(__Method_Average_ClientStreaming, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::Shared.Protos.AverageNumbersRequest, global::Shared.Protos.AverageNumbersResponse>(serviceImpl.Average_ClientStreaming));
      serviceBinder.AddMethod(__Method_Sum_ClientServerBothStreaming, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::Shared.Protos.SumNumbersRequest, global::Shared.Protos.SumNumbersResponse>(serviceImpl.Sum_ClientServerBothStreaming));
    }

  }
}
#endregion
